src/app/components/Contact.js, src/app/components/ContactPlaceholder.js, src/app/components/ExportModal.js, src/app/constants.js, src/app/helpers/decrypt.js
No need to generate public keys from private keys every time a contact is decrypted. We can do it just once for all of them
=> More efficient export modal

src/app/components/ContactEmailSettingsModal.js, src/app/components/ContactGroupModal.js, src/app/components/ContactGroupsModal.js, src/app/components/ContactKeysTable.js, src/app/components/ContactMIMETypeSelect.js, src/app/components/ContactModal.js, src/app/components/ContactPgpSettings.js, src/app/components/ContactPlaceholder.js, src/app/components/ContactSchemeSelect.js, src/app/components/ContactSummary.js, src/app/components/ContactViewProperties.js, src/app/components/ContactViewProperty.js, src/app/components/KeyWarningIcon.js, src/app/components/SelectEmailsModal.js, src/app/constants.js, src/app/content/AuthSidebar.js, src/app/helpers/pgp.js, src/app/helpers/vcard.js
``` js
{
encrypt: Boolean, // Stored in the vCard
sign: Boolean, // Stored in the vCard
scheme: String, // Stored in the vCard
mimeType: String, // Stored in the vCard
trusted: Array<String>, // List of fingerprint we trust and store in the vCard
keys: Array<Object>, // List of keys stored in the vCard
email: String, // Email attached to PGP settings
}
```
Fixes #9
=> Fix #9 - Support PGP settings per contact email

src/app/components/ContactModal.js, src/app/helpers/encrypt.js, src/app/helpers/properties.js
Handle group in vCard properties
Handle pref in vCard properties (email)
=> Clean properties

src/app/components/ContactFieldProperty.js, src/app/components/ContactsList.js, src/app/components/MergeRow.js, src/app/containers/ContactsContainer.js, src/app/content/AuthSidebar.js
=> Fix #29 - Add merge banner in contact list

src/app/components/Contact.js, src/app/components/ContactEmailSettingsModal.js, src/app/components/ContactGroupModal.js, src/app/components/ContactModal.js, src/app/components/ContactView.js, src/app/components/ContactsList.js, src/app/containers/ContactProvider.js, src/app/containers/ContactProviderContext.js, src/app/containers/ContactsContainer.js, src/app/content/PrivateApp.js, src/app/hooks/useContact.js
* Add LRU cache for contacts synchronized with the event manager
=> Contact LRU cache

src/app/containers/ContactsContainer.js
=> Add aside sidebar

src/app/components/ContactImageField.js, src/app/components/ContactSummary.js
Needs: https://github.com/ProtonMail/react-components/pull/142/files
=> Use Image component to load images (#28)

src/app/components/ContactGroupDropdown.js
Replaced old dropdown with the new one.
Gonna fix tests after react-components PR is merged.
=> Fix dropdown for contact group for the new dropdown

src/app/components/ContactEmailSettingsModal.js
=> Fix #45 - POST request with Overwrite 1 doesn't work

src/app/components/ContactEmailSettingsModal.js, src/app/content/PrivateApp.js
Fix: https://github.com/ProtonMail/proton-contacts/issues/42
=> Add ContactGroupModel to event models (#42)

src/app/containers/ContactProvider.js, src/app/containers/ContactsContainer.js
Deleting contact wouldn't invalidate cache.
Fixes: https://github.com/ProtonMail/proton-contacts/issues/69
=> Fix contact delete

src/app/components/ContactFieldProperty.js, src/app/components/ContactLabelProperty.js, src/app/components/ContactModal.js, src/app/components/ContactModalLabel.js, src/app/components/ContactModalRow.js, src/app/components/ContactView.js, src/app/components/import/SelectImportField.js, src/app/components/import/SelectImportType.js, src/app/helpers/decrypt.js, src/app/helpers/fields.js, src/app/helpers/properties.js, src/app/helpers/types.js
- Closes #53.
- Takes care of a bug that would appear for contacts with UID in encrypted cards (put there by mistake)
- Make code more homogeneous
=> Several fixes to add/edit contact modal

src/app/content/PrivateHeader.js
Requires: https://github.com/ProtonMail/react-components/pull/166
=> Add UpgradeButton to PrivateHeader

src/app/helpers/csvFormat.js
=> correct typos in csvFormat

src/app/helpers/csvFormat.js
#83 was not closing #82 properly
Fixes #82
=> fix regex typo

src/app/components/ContactPlaceholder.js, src/app/components/ExportModal.js, src/app/containers/ContactsContainer.js, src/app/helpers/decrypt.js
Apart from the bug described in #56, keys were not loaded when the export started, leading to errors in the decryption of some contacts and therefore their export. Both things are fixed. I also fixed some React warnings regarding closing the modal.
Closes #56
=> Fix bugs in export

src/app/components/ContactToolbar.js, src/app/containers/ContactsContainer.js
Fix https://github.com/ProtonMail/proton-contacts/issues/93
=> Fix #93 - Use memo everywhere

src/app/containers/ContactsContainer.js
Fix https://github.com/ProtonMail/proton-contacts/issues/58
=> Fix #58 - Delete contact

src/app/components/ContactGroupDropdown.js
=> Avoid double counting in contact group dropdown

src/app/components/ContactViewProperty.js
- added a function `applyEllipsisClass` with exceptions in order to manage notes display
Fixes: #91
=> Fix #91 - add exception for note display

src/app/components/ContactsList.js, src/app/containers/ContactsContainer.js
For empty address book:
For no contacts found after search:
=> Add image placeholders

src/app/components/ContactPlaceholder.js, src/app/containers/ContactsContainer.js
The `ContactPlaceholder` component was counting only filtered (by search) contacts. But it should count all of them
=> Count all contacts, not just filtered ones

src/app/components/ContactsList.js
- added `no-outline` helper on `contacts-list` fixed it
Fixes #104
=> Fix #104 - non-necessary outline

src/app/containers/ContactsContainer.js, src/app/containers/SettingsContainer.js
Requires: https://github.com/ProtonMail/react-components/issues/179
=> Pass StorageSpaceStatus to sidebar

src/app/containers/ContactsContainer.js
=> fix broken delete

src/app/components/import/ImportModal.js
=> Typo when getting the extension of a file

src/app/components/ContactGroupDropdown.js
We must force the dropdown component to update upon closing
Fixes #110
=> Fix sticky checkboxes on contact-groups dropdown

src/app/components/ContactGroupDropdownButton.js, src/app/components/ContactToolbar.js
Applied `toolbar-button` classes and fix spacings
=> Fix - add toolbar styles to buttons

src/app/components/ContactPlaceholder.js
Fix alignments in contacts placeholder (spotted by Keven):
Before:
After:
=> Fix alignement of boxes

src/app/components/ContactPlaceholder.js, src/app/components/ContactsList.js, src/app/components/ExportModal.js, src/app/components/import/AttachedFile.js, src/app/components/import/AttachingModalContent.js, src/app/components/import/ErrorDetails.js, src/app/components/import/ImportCsvModalContent.js, src/app/components/import/ImportModal.js, src/app/components/import/ImportingModalContent.js, src/app/containers/ContactsContainer.js, src/app/helpers/csv.js, src/app/helpers/encrypt.js, src/app/helpers/import.js, src/app/helpers/importCsv.js, src/app/helpers/progress.js, test/progress.test.js
=> Improvements to the import modal

src/app/components/ContactPlaceholder.js
- applied some flex helpers to align buttons (same as for a paid user)
Fixes: #151
=> Fix boxes alignment

src/app/components/ContactModalRow.js
- added a modifier for address block, to align it properly with select
- added a case for photo/logo to align action button on top (the alignment was set to bottom)
- bonus; removed inline style for cursors, used helper class for it.
Fixes: #148
=> Fix #148 - aligment of elements

.eslintrc.json, jest.config.js, package.json, src/app/helpers/csvFormat.js, src/assets/logoConfig.js, tsconfig.json
Reordered some functions in code, so that linter if happy.
=> Typescript project configs

src/app/components/ContactModalRow.js, src/app/components/ContactsList.js, src/app/containers/ContactsContainer.js
* Center empty address book image
* Do not underline "Add a contact" nor "Import contact"
Closes #172
=> Modify empty address book layout

src/app/components/ContactModal.js, src/app/components/UpgradeModal.js, src/app/containers/ContactsContainer.js, src/app/content/PrivateSidebar.js
Fix https://github.com/ProtonMail/proton-contacts/issues/171
=> Review sidebar

src/app/containers/SettingsContainer.js, src/app/content/PrivateApp.js, src/app/pages/ContactGroupsPage.js, src/app/pages/GeneralPage.js, src/app/pages/SettingsPage.js
- Split contact settings in 2 tabs
Fix https://github.com/ProtonMail/proton-contacts/issues/168
=> Review contact settings structure

src/app/components/ContactAdrField.js, src/app/components/ContactModal.js, src/app/components/ContactModalRow.js, src/app/components/ContactSummary.js, src/app/components/ContactSummary.scss, src/app/components/ContactView.js, src/app/components/ContactViewProperties.js, src/app/components/UpsellFree.js
=> Review contact form

src/app/components/Contact.js, src/app/components/ContactEmailSettingsModal.js, src/app/components/ContactKeysTable.js, src/app/components/ContactPgpSettings.js, src/app/components/ContactSchemeSelect.js, src/app/components/ContactView.js, src/app/components/ContactViewProperties.js, src/app/components/ContactViewProperty.js, src/app/constants.js, src/app/helpers/pgp.js
I noticed some problems with the PGP settings modal. Some were typos, others were affecting functionality.
=> Fix some bugs with pgp settings modal

src/app/containers/ContactsContainer.js
* Change text according to #169
* Change color according to #169
Closes #169
=> Changes to delete modal

src/app/components/ContactPlaceholder.js, src/app/containers/ContactsContainer.js
Following #164:
- [-] Update icons in both free and paid user. DESIGN MISSING FOR THE THIRD ICON OF FREE USER
Closes #164
=> Changes to welcome message in ContactPlaceholder

src/app/content/PrivateSidebar.js
Just added same styles as on Mail, and centered the main CTA button (spotted by @matstaz).
=> Fix main CTA design

src/app/components/ContactRow.js, src/app/components/ItemCheckbox.js
- Added missing class on icon to achieve requested design (hover on cell/element)
- bonus: added `cursor-pointer` on entire row (to help user understanding that he can click on it, something will happen)
=> Fix - updated design of contact selector

src/app/components/ItemCheckbox.js
Needs https://github.com/ProtonMail/design-system/pull/229
Closes #166
=> Implement hover over states on contacts

src/app/components/import/ImportModal.js
=> File extension should be case-insensitive on import

src/app/components/ContactPlaceholder.js, src/app/containers/ContactsContainer.js, src/app/content/PrivateSidebar.js
=> Do not allow export all if there are no contacts

src/app/components/ContactViewProperty.js
=> Let free user access pgp mail settings

src/app/components/ContactRow.js, src/app/components/ContactsList.js, src/app/components/ItemCheckbox.js
@econdepe I let you merge it when it's OK for you.
Fix https://github.com/ProtonMail/proton-contacts/issues/219
=> Reduce row's height

src/app/components/ContactAdrField.js, src/app/components/ContactFieldProperty.js, src/app/components/ContactModal.js, src/app/components/ContactModalRow.js, src/app/components/ContactViewProperty.js
=> WIP: polish add/edit contact modal

src/app/components/ContactPlaceholder.js
=> Correct typos in welcome message

src/app/components/ContactModalProperties.js, src/app/components/ContactModalRow.js
Address issues in #226
Closes #226
=> Responsive contact modal

src/app/components/ContactGroupDropdown.js, src/app/components/ContactToolbar.js, src/app/containers/ContactsContainer.js, src/app/content/PrivateApp.js, src/app/content/PrivateSidebar.js
When something was loading, it would early return `<Loader>` which in this case removed the entire view
=> Fix #238 - Loading state

src/app/components/ContactPlaceholder.js, src/app/components/ContactView.js, src/app/helpers/export.js
According to #181, a new design is required. We need two things for achieving that:
Closes #181
=> Multi-contact selection

src/app/components/ContactGroupModal.js, src/app/components/ContactToolbar.js, src/app/components/ContactsList.js, src/app/containers/ContactsContainer.js, src/app/containers/SettingsContainer.js, src/app/content/PrivateHeader.js
Implement responsive design of #225.
Closes #225
=> Make contact container responsive

src/app/components/ContactPlaceholder.js
Use ngettext where possible in ContactPlaceholder
=> Proper plurals in ContactPlaceholder

src/app/containers/ContactsContainer.js
Contacts would remain selected when navigating from the contact list to a contact group
=> Fix bad transition when navigating to a contact group with contacts selected

src/app/components/ContactPlaceholder.js, src/app/content/PrivateSidebar.js
=> Disable export button for empty contact group

src/app/containers/ContactsContainer.js
There was a missing Boolean condition in `ContactsContainer`
=> Broken `ContactPlaceholder` for empty address book

src/app/components/ContactPlaceholder.js, src/app/components/ContactsList.js, src/app/containers/ContactsContainer.js
=> Several fixes to Contacts Container

src/app/containers/ContactsContainer.js, src/app/containers/SettingsContainer.js, src/app/content/PrivateLayout.js
Fix https://github.com/ProtonMail/proton-contacts/issues/204
=> Fix #204 - Add title for ProtonContacts

src/app/components/ContactViewProperties.js
=> Display logo in the contact properties

src/app/components/ContactPlaceholder.js
=> Fix typo in export card in welcome message

src/app/components/ContactsList.js, src/app/containers/ContactsContainer.js
The behavior we currently have in `mail` when a few emails are checked but a different one is selected is to remove the check selection and open the selected email. Mimic this behavior in `contacts`
=> Clear selection if a contact is selected

src/app/components/ContactModal.js, src/app/components/ContactsList.js, src/app/constants.js, src/app/containers/ContactsContainer.js, src/app/content/PrivateHeader.js, src/app/content/PrivateSidebar.js
When adding a new contact, display the contact freshly created in the right hand pane
Closes #274
=> Switch to newly-created contact

src/app/containers/ContactsContainer.js
Email key is not set in contact Object.
=> Fix #284 - Search by email stored in contact emails

src/app/containers/ContactsContainer.js, src/app/content/PrivateSidebar.js
=> Clear search on groups navigation

src/app/components/ContactModal.js, src/app/components/import/ImportingModalContent.js, src/app/components/merge/MergingModalContent.js
Api constants have been recently renamed: https://github.com/ProtonMail/proton-shared/pull/68
=> Take into account renamed api constants

src/app/app.scss
React component import will be simplified, in order to allow creating project specific components and avoid using them if they are not needed.
=> WIP: Feat - better css import

src/app/components/ContactModal.js, src/app/components/ContactsList.js, src/app/containers/ContactsContainer.js, src/app/content/PrivateHeader.js, src/app/content/PrivateSidebar.js
=> Clear search when creating a contact

src/app/components/ContactPlaceholder.js, src/app/components/ContactToolbar.js, src/app/components/ContactsList.js, src/app/containers/ContactsContainer.js
The logic for checking contacts was not sharp enough in the code, leading to problems like those described in #316, #318 and #326. This PR improves that logic, and fixes alongside related issues like #324
Closes #318 and #326. Fixes #316 and #324
=> Better logic for checking and deleting contacts

src/app/components/ContactsList.js
Homogeneize the empty-search placeholder with mail v4, as requested by #302
Closes #302
=> Make "clear it" button bold and capitalized

src/app/components/ContactGroupModal.js
=> Better distinction between email and name in ContactGroupModal

src/app/components/ContactViewProperty.js
=> Display standard type for property types in contact view

src/app/helpers/csv.js
=> remove console.log

src/app/components/ContactImageField.js
=> fix alignment of "Upload picture" button in the add/edit contact modal

test/merge.test.js
To test better commit https://github.com/ProtonMail/proton-contacts/commit/5721bf6edb9539a03efdc7f62d6b4611132d7875
=> add more tests for the merge functionality

src/app/containers/ContactsContainer.js
=> add proper class for generic error inside contact view

src/app/containers/ContactsContainer.js, src/app/content/PrivateHeader.js
Fix https://github.com/ProtonMail/proton-contacts/issues/275
=> Switch title for search when on a search is active

src/app/components/ContactPlaceholder.js
=> Better responsiveness for welcome message

src/app/content/PrivateLayout.js
Related to https://github.com/ProtonMail/react-components/issues/459
Requires https://github.com/ProtonMail/react-components/pull/479
=> Pass upgrade button as a prop instead of children

src/app/components/ContactAdrField.js, src/app/components/ContactModalRow.js
=> fix alignments in contact modal for the adr field

src/app/components/ContactsList.js
=> Change list item height to 55

src/app/components/import/ImportCsvModalContent.js, src/app/components/import/ImportCsvTableRows.js, src/app/helpers/csv.js, src/app/helpers/csvFormat.js, src/app/helpers/importCsv.js, src/app/helpers/property.js
* Import csv functionality was broken because of a typo in the code
* Compact name field has been removed from the import csv modal, as it was confusing to have it there since it cannot be modified by the user from the contact modal.
=> Fix broken import csv

src/app/components/ContactViewProperty.js
Use new root address when the url does not include the protocol (HTTP or HTTPS)
Fixes #371
=> Use proper links for URLs stored in vcard

src/app/components/ContactToolbar.js
Use the toolbar component from https://github.com/ProtonMail/react-components/pull/517
=> use new toolbar component
