src/app/components/ContactPlaceholder.js
Some contact groups have the bottom part of their letters cut-off in the view of the right-part of the screen.
This was caused by vertical rythm formulas of the Design System (of course, with user-generated content... ¯\_(ツ)_/¯ ).
- created a helper `lh-standard` in design system to apply standard `line-height` https://github.com/ProtonMail/design-system/commit/0b197d44f9c7c1ca64987e53aba8dad797e92c1d
- applied this helper to contact group name (will also fix emojis issues 🎉 )
Fixes #57 
Before:
After:
=> Fix #57 - contact group name cut off

src/app/components/ContactSummary.js, src/app/components/ContactViewProperty.js
- Incorrect handling of long name/emails
- bad display of button group (icon missing, etc.)
- wrapped buttons in a `flex-item-noshrink` to avoid it being shrinked (this part should not be flexible)
- added `ellipsis` class on elements to activate `text-overflow: ellipsis` when needed (added `title` attribute on mailto, best practice we always do when ellipsis is used)
Bonus : also fixed icon email display when long name, to avoid name being put under this icon
Fixes #52
🎉 (this is my first PR on React project, I really prefer this to Angular 👍  )
=> Fix #52 - handling of long name/emails

src/app/components/ContactModalProperties.js, src/app/components/ContactsList.js, src/app/components/EncryptedIcon.js
By default, tooltips bind scroll events to `.main` or `body`, contact list and modals have their own classes.
=> Fix tooltips scrolling

src/app/components/ContactGroupIcon.js
this component got moved from react-components before my PR got merged
=> Propagate props in contact group icon

src/app/components/ContactGroupDropdown.js
Long name display was broken (alignments, icon shrinking, etc.)
- icon and checkbox can't shrink now (`flex-item-noshrink`)
- text take the fluid (`flex-item-fluid`)
- vertical alignments (`mtauto` `mbauto` stuff)
- padding around item list
Fixes #87 
Before 
After
=> Fix #87 - long names display in add to groups

src/app/components/ContactFieldProperty.js
Although #98 was addressed already in #38, the adr field in the edit modal was not displaying properly simply because it was just taking the first value in the array representing the property. Since only adr properties are array-valued, we don't need some old logic for keeping only the first value of a property in case that is an array (that is taken care somewhere else for properties that we don't expect to be array-valued, like nickname)
Closes #98
=> Fix adr field not displaying

src/app/components/ContactPlaceholder.js, src/app/containers/ContactsContainer.js
- add missing `main-area--withToolbar no-scroll` classes on container (same as Design System website)
- added some `scroll-if-needed` helper for proper scrolling
Fixes #105
=> Fix #105 - add missing structure for proper scrolling

src/app/components/ContactToolbar.js, src/app/containers/ContactsContainer.js
- The contact-groups dropdown was not clickable when a contact was selected but not checked.
- It was possible to click the 'delete' button when no contact was selected or checked, prompting some React errors.
Both things are fixed now.
Closes #108
=> Fix disabled property of buttons in ContactToolBar

src/app/components/ContactGroupDropdown.js, src/app/components/ContactGroupDropdownButton.js
- Refs are objects: `ref = { current: React.Node }`
- `ContactGroupDropdownButton` does not need to be passed `hasCaret` since it uses `DropdownCaret` by definition.
Fixes #111
=> Fix React warnings from contact-group dropdown

src/app/content/PrivateHeader.js
Same as for https://github.com/ProtonMail/protonmail-settings/pull/117 
Some classes were missing, I need them in order to style all projects the same way:
=> Fix top navigation display

src/app/components/import/ImportModal.js
Because #31 is still not closed, it may be better to disable the import-categories step in the import modal, which is currently behaving as a dummy step. Otherwise the QA team may be confused.
=> Disable import categories momentarily in import modal

src/app/helpers/merge.js
There was a mistake in the helper function `linkConnections`. Despite being quite obvious, somehow the function was working properly through many tests... Thanks @emnproton for spotting it!
Fixes #129
=> Fix error in linkConnections

src/app/components/import/AttachedFile.js
Icon alignment in the import contacts modal is not properly set.
- fixed icon alignment
- removed double borders
- added `flex-item-noshrink` to elements that should not be flexible
- also fix display in case of an import with looooooooooooong filename (`ellipsis`, etc.).
Once fix applied:
=> Fix #128 - import contact icon (and other fixes)

src/app/components/Contact.js, src/app/components/ContactView.js, src/app/components/ContactViewProperties.js, src/app/components/ContactViewProperty.js, src/app/components/SelectEmailsModal.js, src/app/containers/ContactsContainer.js
* Issue #130 was simply provoked by having two functions called in inverted order, so that it's simple to fix.
* The icons for contact groups were not being displayed properly in some cases because the emails were being matched with email IDs based on the email address (that works fine as long as there are no email collisions for a given user). I changed that match so that emails are always identified by email ID.
Closes #130
=> Improvements for contact group dropdown

src/app/components/ContactPlaceholder.js
The buttons in ContactPlaceholder are misaligned:
The button for import has a couple of classes (`flex` and `flex-column`) that aligns it with the groups button, but that class is missing for the export, which is therefore not aligned. If that class is added, all buttons become aligned:
I'm not sure whether this could be achieved without so many classes though.
=> Align buttons in ContactPlaceholder

src/app/components/import/ImportCsvTableHeader.js
The buttons in the last header csv table of the import csv modal would render separately as the width of the page is decreased. This fix stitches them together so that they will always render together
Closes #196
=> stick together buttons of csv table

src/app/components/ContactModal.js, src/app/components/UpgradeModal.js
We need to pass `...rest` to the modal for it to close when no `onClose` is passed.
Also, with the new design it's not necessary anymore to have `UpgradeModal` in `ContactModal`
=> Fix upgrade modal not closing

src/app/components/ContactEmailSettingsModal.js
The API does not accept armored keys in the vcard. Instead it needs the base64 string form of the binary key.
Fixes #208
=> Save key in the format that the API wants

src/app/components/ContactEmailSettingsModal.js, src/app/helpers/pgp.js
* keys were marked invalid incorrectly
* key model must be updated when keys are added
This fixes #216 , but I feel we need a more thorough review of the PGP settings modal. I think the code can be improved and some functionality is lacking (e.g. "set primary" button)
=> More fixes to the PGP settings modal

src/app/components/ContactGroupModal.js
Using `label` in the options passed to `<select>` was driving several browsers (Firefox, Safari) crazy. The text inside the options of the select was displayed white, instead of black. Chrome did not have the problem. The other browsers were re-computing the color, making it white
Fixes #237
=> Use text in Select in ContactGroupsModal

src/app/components/ContactPlaceholder.js, src/app/components/ContactsList.js, src/app/containers/ContactsContainer.js
* center placeholder images (empty address book, group and contact multi-selection)
* add `mt2` css class on welcome message
* also, fix wrong use of `main-area--withToolbar--noHeader`. It must only be used when there's no header
=> Center images to align with mail layout

src/app/containers/ContactsContainer.js
Select all should only select filtered contacts. Right now it was selecting everything even if only the filtered contacts are shown in the screen, leading to very dangerous situations (like erasing all contacts by mistake)
=> Fix bug with select all

src/app/components/ContactGroupDropdown.js
Currently it closes when focusing on the modal. No reason not to close it already when opening the modal
=> Close contact group dropdown when opening the ContactGroupModal

src/app/components/ContactsList.js
The code was not correct, missing `contactGroupID`. Therefore the modal opened did not correspond to the empty group
=> Fix edit empty group

src/app/components/ContactEmailSettingsModal.js, src/app/components/ContactModal.js, src/app/components/import/ImportModal.js, src/app/components/merge/MergingModalContent.js, src/app/constants.js, src/app/helpers/import.js, src/app/helpers/merge.js
We were not taking care of categories in several places: when editing contacts (`ContactModal`), when editing email settings (`EmailSettingsModal`), and when merging contacts (`MergingModalContent`). This PR fixes that and polishes the code a little bit
Fixes #270
=> Take care of categories when editing / merging contacts

src/app/components/ContactFieldProperty.js, src/app/components/ContactImageField.js, src/app/components/ContactImageModal.js, src/app/components/ContactImageSummary.js, src/app/components/ContactModalRow.js, src/app/components/ContactSummary.js, src/app/components/ContactViewProperty.js, src/app/constants.js
Implement the suggestions in #231.
For non-square pictures, like 
, we select a circle in the center:
If the image is smaller, we keep the circular shape, but obviously it must be smaller:
Closes #231. Closes #195.
=> Improve UX for pictures in ContactModal

src/app/components/ContactModal.js, src/app/components/import/ImportingModalContent.js, src/app/components/merge/MergingModalContent.js, src/app/constants.js, src/app/containers/ContactsContainer.js
When the user deletes a contact from a contact group, do not navigate away from the group. To achieve that, we can simply keep the contactGroup query parameter in the `location` object.
Also here:
- Rename the constant `SUCCESS_IMPORT_CODE` -> `SUCCESS_API_CODE`, which is more appropriate.
- Check api response codes when deleting a contact (since we're passing an array, some of them could fail)
Closes #283
=> Remain in group after contact delete

src/app/components/ContactsList.js
query search -> search query in "You can either update your query search or ${ clearSearch }."
=> Fix a typo in the "No messages found" screen

src/app/containers/ContactsContainer.js, src/app/content/PrivateSidebar.js
Better https://github.com/ProtonMail/proton-contacts/pull/293
As @EpokK proposed, it's better to clear search when the group param change than when performing the navigation action.
=> Better way to reset search when switching groups

src/app/content/PrivateSidebar.js
Remove unexistent `onClearSeach` prop from `PrivateSidebar.propTypes`
=> Hotfix #299

src/app/components/ContactRow.js, src/app/components/ContactViewProperties.js, src/app/content/PrivateHeader.js
As described in #304, when creating a new group from the contact view and adding the contact in the view to the list, the app crashes. The reason is that the new email labels (for the recently created group) are created before the list of contact groups is updated. This creates a mismatch that the app is unable to handle. It's enough to add a couple of lines to take care of this mismatch.
I also removed a `isRequired` property from a prop because it's not always required.
Fixes #304
=> fix crash when creating new contact group

src/app/components/ContactFieldProperty.js, src/app/components/ContactKeysTable.js, src/app/components/ContactViewProperty.js, src/app/components/ExportModal.js
The crash described in #331 was happening because we were using a deprecated version of the DateInput component in `react-components`, which has been recently changed as part of the migration to the `date-fns` library.
There were a few places in contacts where we were using `moment`. This PR migrates those uses to `date-fns`
Closes #311
=> Use date-fns

src/app/components/ContactImageSummary.js
When clicking on a contact with no image, there was a request to `localhost/undefined`. Somehow this was generated by the helper `toImage` when passed an `undefined` argument, which was happening in the `ContactImageSummary` component. This PR removes the call to `toImage(undefined)`
=> Prevent phantom requests when clicking on contacts with no image

src/app/components/ContactsList.js, src/app/components/import/ImportingModalContent.js, src/app/constants.js, src/app/containers/ContactsContainer.js, src/app/helpers/csv.js, src/app/helpers/csvFormat.js
Bugs on import:
- Capturing csv's using underscore now (first_name -> first name)
- Better capture of several csv properties (mainly addresses, but also photo and logo, ignored before)
- Remove front-end timeout of 30s for the route submitting imported contacts. It seems the response is very slow these days from the back-end. I also reduced the import batch size.
- Improve speed of import by encrypting 5 contacts at a time.
Bugs on delete UX:
- After "delete all", we were not navigating to `/contacts` and we were leaving the checkbox for "check all" ticked.
- Only navigate away from current contact if it's deleted.
- `ContactsPlaceholder` was equal to `0` instead of `null` in some instances.
Fixes #292
Closes #317
Needs https://github.com/ProtonMail/proton-shared/pull/68 and …
=> Fix some import bugs (mainly csv) plus better delete UX

src/app/components/ContactModalLabel.js, src/app/components/ContactModalProperties.js, src/app/components/ContactModalRow.js
Recent changes dislocated the name field in the contact modal. This PR fixes #327
=> Fix bad-looking FN row in contact Modal

src/app/components/ContactImageSummary.js
After a recent change which make images load only after clicking "Load photo", the image loading was slightly broken:
After editing a contact, if the image was small, it wouldn't be updated after closing the modal.
When loading the image, it would flash very quickly the image not rounded, which is ugly if noticed. A loader is being displayed now instead of that quick intermediate step
=> Improve image loading

src/app/helpers/csv.js, src/app/helpers/csvFormat.js
The external library (Papa parse) we're using for parsing CSV files is not doing its job properly on csv files with empty headers (at least when they're in the last column). I added an extra layer of parsing in the code so that empty headers are skipped (I couldn't find how to do it with Papa parse).
Closes #292
=> correct parsing of Papa.parse which goes south with certain csv files

src/app/components/ContactToolbar.js, src/app/components/delete/DeleteModal.js, src/app/containers/ContactsContainer.js
In the last modification to the logic for deleting a contact, we lost in the way the ability to delete the current contact in case it's not checked. This PR recovers this ability. Also, because the delete operation can take some time, it's better to freeze the "confirm deletion" modal while it happens. Otherwise you can go back to the contact view where the deleted contacts are still there
=> Possibility of deleting current (not checked) contact

src/app/helpers/decrypt.js, src/app/helpers/merge.js, src/app/helpers/properties.js, src/app/helpers/vcard.js
For Vcard fields that admit more than one value, there is a PREF parameter that sets the preference of the different values. We were not saving this parameter in the Vcard, leading to the bugs described in #341 and #339.
Fixes #341. Fixes #339
As a sidenote: this bug went undetected till now because somehow the fields were being saved in the right order in the Vcard (without the PREF parameter though), and read back in the same order. That order in the read-back was however altered in Firefox.
=> Manage prefs properly

src/app/helpers/merge.js, test/merge.test.js
Test server: neutron.protonmail.blue
When merging two contacts, if two string values for a property differ only in capitalization or trailing spaces, assume the properties are the same and merge them.
Closes #323
=> Make merge capitalization-insensitive except for mail

src/app/components/ContactEmailSettingsModal.js, src/app/components/ContactKeysTable.js, src/app/components/ContactPgpSettings.js, src/app/components/KeyWarningIcon.js, src/app/containers/ContactsContainer.js, src/app/helpers/pgp.js, src/app/helpers/properties.js, src/app/helpers/property.js
Test server: https://eta.protonmail.blue/contacts
Note for testers: protonmail.com addresses behave as WKD addresses for protonmail.blue users. I.e., if in your blue account you have a protonmail contact, it should have WKD keys.
Implementation of WKD according to the one in v3: https://github.com/ProtonMail/Angular/pull/9063 , with a few slight improvements. The flow for the PGP settings modal (the one that opens when clicking on advanced settings for an email address) in the three possible cases is as follows:
A flag 'ACTIVE' is displayed for the key that is currently used for encryption, if any. In v3 it was 'PRIMARY', but it was only displayed for pinned keys, which was a bit confusing. "Set as primary" has been substituted by "Use for sending". This has been discussed with @twiss. …
=> Implement WKD

src/app/components/ContactKeysTable.js, src/app/components/ContactPgpSettings.js
There's a mismatch between the labels we use in the keys tables that appear in Mail/Settings/Keys and Contacts/Email-Settings/Advanced-Contact-Editor. In the former, we use ACTIVE for keys that are not expired or revoked, and PRIMARY to indicate the key that is currently being used to encrypt incoming emails. In the latter, we use ACTIVE to indicated the key that is currently being used for encrypting outgoing emails. This is probably gonna be confusing for the user.
=> Change key labels and add new notifications

src/app/components/ContactsList.js
Some image placeholders have been deprecated
=> use no-result-search.svg instead of no-results-found.svg
